#!/usr/bin/env bash
#this script displays the currently running process with a user oriented formats of all processes, for all users, including those which might not have a TT in a hierachial orientations
ps -A uf