#!/usr/bin/env bash
# This script that loops 100 times and displays "FizzBuzz" when a number is a multiple of 3 and 5, "Fizz" for a multiple of 3, "Buzz" for a multiple of 5, otherwise display the number.
for j in {1..100}; do
    three=$((j%3))
    five=$((j%5))

    if [ $five -eq 0 ] && [ $three -eq 0 ]; then
	echo "FizzBuzz"
    elif  [ $three -eq 0 ]; then
	echo "Fizz"
    elif [ $five -eq 0 ]; then
	echo "Buzz"
    else
	echo "$j"
    fi
done
